export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const LOGOUT_USER = 'LOGOUT_USER';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';

export const UPDATE_GENERAL_SETTINGS = 'UPDATE_GENERAL_SETTINGS';
export const UPDATE_GENERAL_SETTINGS_SUCCESS = 'UPDATE_GENERAL_SETTINGS_SUCCESS';
export const UPDATE_GENERAL_SETTINGS_FAIL = 'UPDATE_GENERAL_SETTINGS_FAIL';

export const UPDATE_LIBRARY_SETTINGS = 'UPDATE_LIBRARY_SETTINGS';
export const UPDATE_LIBRARY_SETTINGS_SUCCESS = 'UPDATE_LIBRARY_SETTINGS_SUCCESS';
export const UPDATE_LIBRARY_SETTINGS_FAIL = 'UPDATE_LIBRARY_SETTINGS_FAIL';

export const FETCH_GROUP_MEMBERSHIPS = 'FETCH_GROUP_MEMBERSHIPS';
export const FETCH_GROUP_MEMBERSHIPS_SUCCESS = 'FETCH_GROUP_MEMBERSHIPS_SUCCESS';
export const FETCH_GROUP_MEMBERSHIPS_FAIL = 'FETCH_GROUP_MEMBERSHIPS_FAIL';

export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_FAIL = 'FETCH_CURRENT_USER_FAIL';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const FETCH_USER_NETWORK = 'FETCH_USER_NETWORK';
export const FETCH_USER_NETWORK_SUCCESS = 'FETCH_USER_NETWORK_SUCCESS';
export const FETCH_NETWORK_FOLLOW = 'FETCH_NETWORK_FOLLOW';
export const FETCH_USER_NETWORK_FAIL = 'FETCH_USER_NETWORK_FAIL';

export const FETCH_USER_FAVORITES = 'FETCH_USER_FAVORITES';
export const FETCH_USER_FAVORITES_SUCCESS = 'FETCH_USER_FAVORITES_SUCCESS';
export const FETCH_USER_FAVORITES_FAIL = 'FETCH_USER_FAVORITES_FAIL';

export const FETCH_USER_LIBRARY = 'FETCH_USER_LIBRARY';
export const FETCH_USER_LIBRARY_SUCCESS = 'FETCH_USER_LIBRARY_SUCCESS';
export const FETCH_USER_LIBRARY_FAIL = 'FETCH_USER_LIBRARY_FAIL';

export const UPDATE_USER_LIBRARY_ENTRY = 'UPDATE_USER_LIBRARY_ENTRY';

export const FETCH_USER_LIBRARY_TYPE = 'FETCH_USER_LIBRARY_TYPE';
export const FETCH_USER_LIBRARY_TYPE_SUCCESS = 'FETCH_USER_LIBRARY_TYPE_SUCCESS';
export const FETCH_USER_LIBRARY_TYPE_FAIL = 'FETCH_USER_LIBRARY_TYPE_FAIL';

export const FETCH_USER_FEED = 'FETCH_USER_FEED';
export const FETCH_USER_FEED_SUCCESS = 'FETCH_USER_FEED_SUCCESS';
export const FETCH_USER_FEED_FAIL = 'FETCH_USER_FEED_FAIL';

export const FETCH_MEDIA = 'FETCH_MEDIA';
export const FETCH_MEDIA_SUCCESS = 'FETCH_MEDIA_SUCCESS';
export const FETCH_MEDIA_FAIL = 'FETCH_MEDIA_FAIL';

export const FETCH_MEDIA_CASTINGS = 'FETCH_MEDIA_CASTINGS';
export const FETCH_MEDIA_CASTINGS_SUCCESS = 'FETCH_MEDIA_CASTINGS_SUCCESS';
export const FETCH_MEDIA_CASTINGS_FAIL = 'FETCH_MEDIA_CASTINGS_FAIL';

export const FETCH_MEDIA_REACTIONS = 'FETCH_MEDIA_REACTIONS';
export const FETCH_MEDIA_REACTIONS_SUCCESS = 'FETCH_MEDIA_REACTIONS_SUCCESS';
export const FETCH_MEDIA_REACTIONS_FAIL = 'FETCH_MEDIA_REACTIONS_FAIL';

export const SEARCH = 'SEARCH';
export const SEARCH_MORE = 'SEARCH_MORE';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_MORE = 'GET_CATEGORIES_MORE';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

export const GET_STREAMERS = 'GET_STREAMERS';
export const GET_STREAMERS_SUCCESS = 'GET_STREAMERS_SUCCESS';
export const GET_STREAMERS_FAIL = 'GET_STREAMERS_FAIL';

export const ONESIGNAL_ID_RECEIVED = 'ONESIGNAL_ID_RECEIVED';
export const CREATE_PLAYER = 'CREATE_PLAYER';
export const CREATE_PLAYER_SUCCESS = 'CREATE_PLAYER_SUCCESS';
export const CREATE_PLAYER_FAIL = 'CREATE_PLAYER_FAIL';

export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_MORE = 'GET_NOTIFICATIONS_MORE';
export const GET_NOTIFICATIONS_LESS = 'GET_NOTIFICATIONS_LESS';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAIL = 'GET_NOTIFICATIONS_FAIL';

export const GET_USER_FEED = 'GET_USER_FEED';
export const GET_USER_FEED_MORE = 'GET_USER_FEED_MORE';
export const GET_USER_FEED_LESS = 'GET_USER_FEED_LESS';
export const GET_USER_FEED_SUCCESS = 'GET_USER_FEED_SUCCESS';
export const GET_USER_FEED_FAIL = 'GET_USER_FEED_FAIL';

export const GET_MEDIA_FEED = 'GET_MEDIA_FEED';
export const GET_MEDIA_FEED_MORE = 'GET_MEDIA_FEED_MORE';
export const GET_MEDIA_FEED_LESS = 'GET_MEDIA_FEED_LESS';
export const GET_MEDIA_FEED_SUCCESS = 'GET_MEDIA_FEED_SUCCESS';
export const GET_MEDIA_FEED_FAIL = 'GET_MEDIA_FEED_FAIL';

export const GET_FBUSER = 'GET_FBUSER';
export const CLEAR_FBUSER = 'CLEAR_FBUSER';
export const GET_FBUSER_SUCCESS = 'GET_FBUSER_SUCCESS';
export const GET_FBUSER_FAIL = 'GET_FBUSER_FAIL';

export const ALGOLIA_KEY_REQUEST = 'ALGOLIA_KEY_REQUEST';
export const ALGOLIA_KEY_SUCCESS = 'ALGOLIA_KEY_SUCCESS';
export const ALGOLIA_KEY_FAIL = 'ALGOLIA_KEY_FAIL';

export const USER_FOLLOW_REQUEST = 'USER_FOLLOW_REQUEST';
export const USER_FOLLOW_SUCCESS = 'USER_FOLLOW_SUCCESS';
export const USER_FOLLOW_FAIL = 'USER_FOLLOW_FAIL';

export const CAPTURE_USERS_DATA = 'CAPTURE_USERS_DATA';
