export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const LOGOUT_USER = 'LOGOUT_USER';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';

export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_FAIL = 'FETCH_CURRENT_USER_FAIL';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const FETCH_USER_NETWORK = 'FETCH_USER_NETWORK';
export const FETCH_USER_NETWORK_SUCCESS = 'FETCH_USER_NETWORK_SUCCESS';
export const FETCH_NETWORK_FOLLOW = 'FETCH_NETWORK_FOLLOW';
export const FETCH_USER_NETWORK_FAIL = 'FETCH_USER_NETWORK_FAIL';

export const FETCH_USER_FAVORITES = 'FETCH_USER_FAVORITES';
export const FETCH_USER_FAVORITES_SUCCESS = 'FETCH_USER_FAVORITES_SUCCESS';
export const FETCH_USER_FAVORITES_FAIL = 'FETCH_USER_FAVORITES_FAIL';

export const FETCH_USER_LIB_ENTRIES = 'FETCH_USER_LIB_ENTRIES';
export const FETCH_USER_LIB_ENTRIES_SUCCESS = 'FETCH_USER_LIB_ENTRIES_SUCCESS';
export const FETCH_USER_LIB_ENTRIES_FAIL = 'FETCH_USER_LIB_ENTRIES_FAIL';

export const FETCH_MEDIA = 'FETCH_MEDIA';
export const FETCH_MEDIA_SUCCESS = 'FETCH_MEDIA_SUCCESS';
export const FETCH_MEDIA_FAIL = 'FETCH_MEDIA_FAIL';

export const FETCH_MEDIA_CASTINGS = 'FETCH_MEDIA_CASTINGS';
export const FETCH_MEDIA_CASTINGS_SUCCESS = 'FETCH_MEDIA_CASTINGS_SUCCESS';
export const FETCH_MEDIA_CASTINGS_FAIL = 'FETCH_MEDIA_CASTINGS_FAIL';

export const FETCH_MEDIA_REVIEWS = 'FETCH_MEDIA_REVIEWS';
export const FETCH_MEDIA_REVIEWS_SUCCESS = 'FETCH_MEDIA_REVIEWS_SUCCESS';
export const FETCH_MEDIA_REVIEWS_FAIL = 'FETCH_MEDIA_REVIEWS_FAIL';

export const SEARCH = 'SEARCH';
export const SEARCH_MORE = 'SEARCH_MORE';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_MORE = 'GET_CATEGORIES_MORE';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

export const GET_STREAMERS = 'GET_STREAMERS';
export const GET_STREAMERS_SUCCESS = 'GET_STREAMERS_SUCCESS';
export const GET_STREAMERS_FAIL = 'GET_STREAMERS_FAIL';

export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_MORE = 'GET_NOTIFICATIONS_MORE';
export const GET_NOTIFICATIONS_LESS = 'GET_NOTIFICATIONS_LESS';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAIL = 'GET_NOTIFICATIONS_FAIL';

export const GET_USER_FEED = 'GET_USER_FEED';
export const GET_USER_FEED_MORE = 'GET_USER_FEED_MORE';
export const GET_USER_FEED_LESS = 'GET_USER_FEED_LESS';
export const GET_USER_FEED_SUCCESS = 'GET_USER_FEED_SUCCESS';
export const GET_USER_FEED_FAIL = 'GET_USER_FEED_FAIL';

export const GET_FBUSER = 'GET_FBUSER';
export const CLEAR_FBUSER = 'CLEAR_FBUSER';
export const GET_FBUSER_SUCCESS = 'GET_FBUSER_SUCCESS';
export const GET_FBUSER_FAIL = 'GET_FBUSER_FAIL';
