export default [
  {
    title: 'Action',
    selected: false,
    subCategoryLength: 0,
    id: 150,
  },
  {
    title: 'Adventure',
    selected: false,
    subCategoryLength: 0,
    id: 157,
  },
  {
    title: 'Comedy',
    selected: false,
    subCategoryLength: 0,
    id: 160,
  },
  // {
  //   title: 'Ecchi',
  //   selected: false,
  //   subCategoryLength: 0,
  // },
  {
    title: 'Fantasy',
    selected: false,
    subCategoryLength: 0,
    id: 156,
  },
  {
    title: 'Harem',
    selected: false,
    subCategoryLength: 0,
    id: 165,
  },
  {
    title: 'Psychological',
    selected: false,
    subCategoryLength: 0,
    id: 232,
  },
  {
    title: 'Romance',
    selected: false,
    subCategoryLength: 0,
    id: 164,
  },
  {
    title: 'Science Fiction',
    selected: false,
    subCategoryLength: 0,
    id: 155,
  },
  {
    title: 'Super Power',
    selected: false,
    subCategoryLength: 0,
    id: 47,
  },
  {
    title: 'Fantasy World',
    selected: false,
    subCategoryLength: 0,
    id: 52,
  },
  {
    title: 'Parallel Universe',
    selected: false,
    subCategoryLength: 0,
    id: 147,
  },
  {
    title: 'Past',
    selected: false,
    subCategoryLength: 0,
    id: 49,
  },
  {
    title: 'Coming of Age',
    selected: false,
    subCategoryLength: 0,
    id: 185,
  },
  {
    title: 'Crime',
    selected: false,
    subCategoryLength: 0,
    id: 175,
  },
  {
    title: 'Cooking',
    selected: false,
    subCategoryLength: 0,
    id: 18,
  },
  {
    title: 'Daily Life',
    selected: false,
    subCategoryLength: 0,
    id: 169,
  },
  {
    title: 'Disaster',
    selected: false,
    subCategoryLength: 0,
    id: 176,
  },
  {
    title: 'Friendship',
    selected: false,
    subCategoryLength: 0,
    id: 167,
  },
  {
    title: 'Law and Order',
    selected: false,
    subCategoryLength: 0,
    id: 183,
  },
  {
    title: 'Military',
    selected: false,
    subCategoryLength: 0,
    id: 207,
  },
  {
    title: 'Politics',
    selected: false,
    subCategoryLength: 0,
    id: 171,
  },
  {
    title: 'School Life',
    selected: false,
    subCategoryLength: 0,
    id: 172,
  },
  {
    title: 'Sports',
    selected: false,
    subCategoryLength: 0,
    id: 180,
  },
  {
    title: 'Revenge',
    selected: false,
    subCategoryLength: 0,
    id: 178,
  },
  {
    title: 'Magical Girl',
    selected: false,
    subCategoryLength: 0,
    id: 37,
  },
];
