import I18n from 'kitsu/translations/i18n';

export const genres = [
  (I18n.t("utils.genres.action")),
  (I18n.t("utils.genres.adventure")),
  (I18n.t("utils.genres.anime Influenced")),
  (I18n.t("utils.genres.cars")),
  (I18n.t("utils.genres.comedy")),
  (I18n.t("utils.genres.cooking")),
  (I18n.t("utils.genres.crime")),
  (I18n.t("utils.genres.dementia")),
  (I18n.t("utils.genres.demons")),
  (I18n.t("utils.genres.documentary")),
  (I18n.t("utils.genres.doujinshi")),
  (I18n.t("utils.genres.drama")),
  (I18n.t("utils.genres.ecchi")),
  (I18n.t("utils.genres.family")),
  (I18n.t("utils.genres.fantasy")),
  (I18n.t("utils.genres.food")),
  (I18n.t("utils.genres.friendship")),
  (I18n.t("utils.genres.game")),
  (I18n.t("utils.genres.gender Bender")),
  (I18n.t("utils.genres.gore")),
  (I18n.t("utils.genres.harem")),
  (I18n.t("utils.genres.hentai")),
  (I18n.t("utils.genres.historical")),
  (I18n.t("utils.genres.horror")),
  (I18n.t("utils.genres.kids")),
  (I18n.t("utils.genres.law")),
  (I18n.t("utils.genres.magic")),
  (I18n.t("utils.genres.mahou Shoujo")),
  (I18n.t("utils.genres.mahou Shounen")),
  (I18n.t("utils.genres.martial Arts")),
  (I18n.t("utils.genres.mature")),
  (I18n.t("utils.genres.mecha")),
  (I18n.t("utils.genres.medical")),
  (I18n.t("utils.genres.military")),
  (I18n.t("utils.genres.music")),
  (I18n.t("utils.genres.mystery")),
  (I18n.t("utils.genres.parody")),
  (I18n.t("utils.genres.police")),
  (I18n.t("utils.genres.political")),
  (I18n.t("utils.genres.psychological")),
  (I18n.t("utils.genres.racing")),
  (I18n.t("utils.genres.romance")),
  (I18n.t("utils.genres.samurai")),
  (I18n.t("utils.genres.school")),
  (I18n.t("utils.genres.sci-Fi")),
  (I18n.t("utils.genres.shoujo Ai")),
  (I18n.t("utils.genres.shounen Ai")),
  (I18n.t("utils.genres.slice of Life")),
  (I18n.t("utils.genres.space")),
  (I18n.t("utils.genres.sports")),
  (I18n.t("utils.genres.super Power")),
  (I18n.t("utils.genres.supernatural")),
  (I18n.t("utils.genres.thriller")),
  (I18n.t("utils.genres.tokusatsu")),
  (I18n.t("utils.genres.tragedy")),
  (I18n.t("utils.genres.vampire")),
  (I18n.t("utils.genres.workplace")),
  (I18n.t("utils.genres.yaoi")),
  (I18n.t("utils.genres.youth")),
  (I18n.t("utils.genres.yuri")),
  (I18n.t("utils.genres.zombies")),
];
