export const FEED_DATA = [
  {
    createdAt: '2017-10-10T01:18:19.280Z',
    updatedAt: '2017-10-10T01:19:04.777Z',
    content: 'My childhood anime!',
    contentFormatted: '<p>My childhood anime!</p>\n',
    commentsCount: 4,
    postLikesCount: 0,
    spoiler: true,
    nsfw: false,
    blocked: false,
    deletedAt: null,
    topLevelCommentsCount: 3,
    editedAt: null,
    targetInterest: null,
    embed: null,
    embedUrl: null,

    comments: [
      {
        id: '28778670',
        type: 'comments',
        links: {
          self: 'https://kitsu.io/api/edge/comments/28778670',
        },
        attributes: {
          createdAt: '2017-10-10T01:19:00.028Z',
          updatedAt: '2017-10-10T01:19:00.028Z',
          content: 'This is new comment',
          contentFormatted: '<p>This is new comment</p>\n',
          blocked: false,
          deletedAt: null,
          likesCount: 0,
          repliesCount: 0,
          editedAt: null,
          embed: null,
          embedUrl: null,
        },
      },
      {
        id: '28778668',
        type: 'comments',
        links: {
          self: 'https://kitsu.io/api/edge/comments/28778668',
        },
        attributes: {
          createdAt: '2017-10-10T01:18:51.205Z',
          updatedAt: '2017-10-10T01:19:04.775Z',
          content: 'This is another comment',
          contentFormatted: '<p>This is another comment</p>\n',
          blocked: false,
          deletedAt: null,
          likesCount: 1,
          repliesCount: 0,
          editedAt: null,
          embed: null,
          embedUrl: null,
        },
      },
    ],
  },
  {
    createdAt: '2017-10-09T15:18:19.280Z',
    updatedAt: '2017-10-10T01:19:04.777Z',
    content: 'My childhood anime!',
    contentFormatted: '<p>My childhood anime!</p>\n',
    commentsCount: 4,
    postLikesCount: 0,
    spoiler: true,
    nsfw: false,
    blocked: false,
    deletedAt: null,
    topLevelCommentsCount: 3,
    editedAt: null,
    targetInterest: null,
    embed: null,
    embedUrl: null,

    comments: [
      {
        id: '28778670',
        type: 'comments',
        links: {
          self: 'https://kitsu.io/api/edge/comments/28778670',
        },
        attributes: {
          createdAt: '2017-10-10T01:19:00.028Z',
          updatedAt: '2017-10-10T01:19:00.028Z',
          content: 'This is new comment',
          contentFormatted: '<p>This is new comment</p>\n',
          blocked: false,
          deletedAt: null,
          likesCount: 0,
          repliesCount: 0,
          editedAt: null,
          embed: null,
          embedUrl: null,
        },
      },
      {
        id: '28778668',
        type: 'comments',
        links: {
          self: 'https://kitsu.io/api/edge/comments/28778668',
        },
        attributes: {
          createdAt: '2017-10-10T01:18:51.205Z',
          updatedAt: '2017-10-10T01:19:04.775Z',
          content: 'This is another comment',
          contentFormatted: '<p>This is another comment</p>\n',
          blocked: false,
          deletedAt: null,
          likesCount: 1,
          repliesCount: 0,
          editedAt: null,
          embed: null,
          embedUrl: null,
        },
      },
    ],
  },
  {
    createdAt: '2017-10-06T13:28:19.280Z',
    updatedAt: '2017-10-10T01:19:04.777Z',
    content: 'My childhood anime!',
    contentFormatted: '<p>My childhood anime!</p>\n',
    commentsCount: 4,
    postLikesCount: 0,
    spoiler: true,
    nsfw: false,
    blocked: false,
    deletedAt: null,
    topLevelCommentsCount: 3,
    editedAt: null,
    targetInterest: null,
    embed: null,
    embedUrl: null,

    comments: [
      {
        id: '28778670',
        type: 'comments',
        links: {
          self: 'https://kitsu.io/api/edge/comments/28778670',
        },
        attributes: {
          createdAt: '2017-10-10T01:19:00.028Z',
          updatedAt: '2017-10-10T01:19:00.028Z',
          content: 'This is new comment',
          contentFormatted: '<p>This is new comment</p>\n',
          blocked: false,
          deletedAt: null,
          likesCount: 0,
          repliesCount: 0,
          editedAt: null,
          embed: null,
          embedUrl: null,
        },
      },
      {
        id: '28778668',
        type: 'comments',
        links: {
          self: 'https://kitsu.io/api/edge/comments/28778668',
        },
        attributes: {
          createdAt: '2017-10-10T01:18:51.205Z',
          updatedAt: '2017-10-10T01:19:04.775Z',
          content: 'This is another comment',
          contentFormatted: '<p>This is another comment</p>\n',
          blocked: false,
          deletedAt: null,
          likesCount: 1,
          repliesCount: 0,
          editedAt: null,
          embed: null,
          embedUrl: null,
        },
      },
    ],
  },
];
