export const FEED_DATA = [
  {
    createdAt: '2017-10-10T01:18:19.280Z',
    updatedAt: '2017-10-10T01:19:04.777Z',
    content: 'Huh, aren’t they already doing that with the ‘extension’ of Gundam the Origins? I mean, the battle of Loum is just literally inches away from the colony drop tragedy and the assault on Side 7 where episode 1 of MSG. Huh, aren’t they already doing that with the ‘extension’ of Gundam the Origins? I mean, the battle of Loum is just literally inches away from the colony drop tragedy and the assault on Side 7 where episode 1 of MSG. Huh, aren’t they already doing that with the ‘extension’ of Gundam the Origins? I mean, the battle of Loum is just literally inches away from the colony drop tragedy and the assault on Side 7 where episode 1 of MSG.',
    contentFormatted: '<p>My childhood anime!</p>\n',
    commentsCount: 4,
    postLikesCount: 0,
    spoiler: true,
    nsfw: false,
    blocked: false,
    deletedAt: null,
    topLevelCommentsCount: 3,
    editedAt: null,
    targetInterest: null,
    embed: null,
    embedUrl: null,

    comments: [
      {
        id: '28778670',
        type: 'comment  s',
        links: {
          self: 'https://kitsu.io/api/edge/comments/28778670',
        },
        attributes: {
          createdAt: '2017-10-10T01:19:00.028Z',
          updatedAt: '2017-10-10T01:19:00.028Z',
          content: 'Hey! congrats on graduating. I’ve still got two years to go.',
          contentFormatted: '<p>This is new comment</p>\n',
          blocked: false,
          deletedAt: null,
          likesCount: 0,
          repliesCount: 0,
          editedAt: null,
          embed: null,
          embedUrl: null,
        },
      },
      {
        id: '28778668',
        type: 'comments',
        links: {
          self: 'https://kitsu.io/api/edge/comments/28778668',
        },
        attributes: {
          createdAt: '2017-10-10T01:18:51.205Z',
          updatedAt: '2017-10-10T01:19:04.775Z',
          content: 'This is short comment',
          contentFormatted: '<p>This is another comment</p>\n',
          blocked: false,
          deletedAt: null,
          likesCount: 1,
          repliesCount: 0,
          editedAt: null,
          embed: null,
          embedUrl: null,
        },
      },
    ],
  },
  {
    createdAt: '2017-10-09T15:18:19.280Z',
    updatedAt: '2017-10-10T01:19:04.777Z',
    content: 'At the behest of @Doaks and several others on Kitsu, I’m going to be listing off someone of my favorite/most influential anime in no particular order. First, some background: I have been watching anime for nearly all my life. I remember watching the original Pokémon as it aired and staying at my maternal grandmother’s house to watch Digimon and Beyblade. Toonami introduced me to Naruto, Zatch Bell, and One Piece. However, I got into anime knowing what it was and how it was',
    contentFormatted: '<p>My childhood anime!</p>\n',
    commentsCount: 4,
    postLikesCount: 0,
    spoiler: true,
    nsfw: false,
    blocked: false,
    deletedAt: null,
    topLevelCommentsCount: 3,
    editedAt: null,
    targetInterest: null,
    embed: null,
    embedUrl: null,

    comments: [
      {
        id: '28778670',
        type: 'comments',
        links: {
          self: 'https://kitsu.io/api/edge/comments/28778670',
        },
        attributes: {
          createdAt: '2017-10-10T01:19:00.028Z',
          updatedAt: '2017-10-10T01:19:00.028Z',
          content: 'Idk about this, but I guess we’ll have to wait and see how it turns out.',
          contentFormatted: '<p>This is new comment</p>\n',
          blocked: false,
          deletedAt: null,
          likesCount: 0,
          repliesCount: 0,
          editedAt: null,
          embed: null,
          embedUrl: null,
        },
      },
      {
        id: '28778668',
        type: 'comments',
        links: {
          self: 'https://kitsu.io/api/edge/comments/28778668',
        },
        attributes: {
          createdAt: '2017-10-10T01:18:51.205Z',
          updatedAt: '2017-10-10T01:19:04.775Z',
          content: 'This is another comment',
          contentFormatted: '<p>This is another comment</p>\n',
          blocked: false,
          deletedAt: null,
          likesCount: 1,
          repliesCount: 0,
          editedAt: null,
          embed: null,
          embedUrl: null,
        },
      },
    ],
  },
  {
    createdAt: '2017-10-06T13:28:19.280Z',
    updatedAt: '2017-10-10T01:19:04.777Z',
    content: 'Well, internet is crapping out. Guess that means it\'s time to watch some anime!',
    contentFormatted: '<p>My childhood anime!</p>\n',
    commentsCount: 4,
    postLikesCount: 0,
    spoiler: true,
    nsfw: false,
    blocked: false,
    deletedAt: null,
    topLevelCommentsCount: 3,
    editedAt: null,
    targetInterest: null,
    embed: null,
    embedUrl: null,

    comments: [
      {
        id: '28778670',
        type: 'comments',
        links: {
          self: 'https://kitsu.io/api/edge/comments/28778670',
        },
        attributes: {
          createdAt: '2017-10-10T01:19:00.028Z',
          updatedAt: '2017-10-10T01:19:00.028Z',
          content: 'This is new comment',
          contentFormatted: '<p>This is new comment</p>\n',
          blocked: false,
          deletedAt: null,
          likesCount: 0,
          repliesCount: 0,
          editedAt: null,
          embed: null,
          embedUrl: null,
        },
      },
      {
        id: '28778668',
        type: 'comments',
        links: {
          self: 'https://kitsu.io/api/edge/comments/28778668',
        },
        attributes: {
          createdAt: '2017-10-10T01:18:51.205Z',
          updatedAt: '2017-10-10T01:19:04.775Z',
          content: 'This is another comment',
          contentFormatted: '<p>This is another comment</p>\n',
          blocked: false,
          deletedAt: null,
          likesCount: 1,
          repliesCount: 0,
          editedAt: null,
          embed: null,
          embedUrl: null,
        },
      },
    ],
  },
];
